project:
  type: website
  preview:
    port: 4200
  resources:
    - "_assets/img"
    - "_assets/font"

website:
  page-navigation: false
  title: "Nonstationary Rainfall Frequency Estimates for Texas"
  description: "James Doss-Gollin's Presentation at AGU 2023 Fall Meeting"
  site-url: https://jdossgollin.github.io/presentation-2023-agu
  repo-url: https://www.github.com/jdossgollin/presentation-2023-agu
  repo-actions: [edit, issue]
  open-graph: true

# citations
bibliography: _bibliography/library-bibtex.bib
csl: _assets/references/american-geophysical-union.csl